chum2987/freemarket_sample_68a

app/assets/javascripts/items.coffee
app/assets/stylesheets/items.scss
app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/views/items/index.html.erb
config/routes.rb
test/controllers/items_controller_test.rb

itemsコントローラー、items.index.erbを作成した。
itemの一覧ページは参考にするフリーマケットアプリのメインページとなるので、土台を作成するため。

itemsコントローラー、indexのviewを追加

---

app/controllers/application_controller.rb
config/deploy.rb
config/deploy/production.rb

本番環境にベーシック認証を追加した。
間違ってサイトにアクセスしたユーザーに誤解を生まないよう、閲覧するユーザーを制限するため。

ベーシック認証の追加

---

README.md

テーブル間のカラムの変更を行なった。
実装を進めていくうちに必要なカラムが変わったため。

READMEの内容変更

---

app/assets/stylesheets/modules/_buy-check.scss
app/views/items/buy-check.html.haml

商品の購入確認ページを実装する
間違って購入しないように確認のページが必要なため
商品購入確認ページの画像です
https://gyazo.com/6fc81c7e015dc8acaf36cd87c2777f5f
コードレビューお願いします！

[WIP]商品購入確認ページ実装

---

app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
db/schema.rb

新規会員登録画面で不要なコードの削除行った。
それぞれビューの実装が行ったん終わったので、内容を取り込み、ローカル環境で確認してみたところ、deviseのテンプレートのhamlも取り込んでしまっていたみたいでビューが崩れたため。

新規会員登録画面の修正

---

app/assets/stylesheets/modules/_items.new.scss
app/controllers/items_controller.rb
app/views/items/new.html.haml

#What
商品出品ビューのフッターを部分テンプレートで統一する
#Why
部分テンプレートを使い回すことでコードの統一化がされ、まとまりがでる。

商品出品ビューのフッターの修正

---

app/assets/stylesheets/modules/_app-banner.scss
app/views/layouts/_app-banner.html.haml

本番環境に画像の反映

---

app/assets/stylesheets/modules/_app-banner.scss
app/views/layouts/_app-banner.html.haml

Reverts chum2987/freemarket_sample_68a#31
パス指定が間違っていたのでrevertを行いました。

Revert "本番環境に画像の反映"

---

app/views/layouts/_header.html.haml
db/schema.rb

ヘッダーのFURIMAロゴにメインページへのパス指定を行った。
スムーズに画面遷移できるようにするため。

タイトルロゴのパス指定

---

app/assets/javascripts/item_images.coffee
app/assets/javascripts/items.coffee
app/assets/stylesheets/item_images.scss
app/controllers/item_images_controller.rb
app/helpers/item_images_helper.rb
app/models/item_image.rb
config/routes.rb
db/migrate/20200504140837_create_item_images.rb
db/schema.rb
test/controllers/item_images_controller_test.rb
test/fixtures/item_images.yml
test/models/item_image_test.rb

＃What
商品画像を登録をするテーブル
＃Whay
ここに商品画像が登録できることで
・商品出品
・トップページ一覧表示
・商品画像の編集
などが可能となる

[WIP]item_imageテーブル作成

---

app/controllers/items_controller.rb
app/views/items/new.html.haml

#What
商品出品ページのカテゴリボックスの作成。
カテゴリーテーブルと連携して表示できるようにする。
なお、子カテゴリと孫カテゴリについてはAjax通信を使う必要があるため一度この時点でプルリクエストを出します。
#Why
商品を出品するにあたりカテゴリの設定をすることはより検索しやすく見やすい商品表示のために
必要である。

[WIP]出品ページのカテゴリボックスの作成

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_category.index.scss
app/controllers/categories_controller.rb
app/views/categories/index.html.haml

カテゴリ一覧ページ、そのカテゴリへのパス指定を行った。
※遷移先のページについては未実装。
フリマアプリ必須実装機能のため。
[![Screenshot from Gyazo](https://gyazo.com/4ef4a0041bbf116590de15393a896728/raw)](https://gyazo.com/4ef4a0041bbf116590de15393a896728)

カテゴリ一覧ページ実装

---

app/assets/stylesheets/modules/_category.scss
app/views/layouts/_header.html.haml

カテゴリー一覧ページへのパス指定を行った。
みやすさが向上するため。

ヘッダーのカテゴリーボタンからカテゴリ一覧ページへのパス指定

---

app/assets/stylesheets/modules/_mypage-address.scss
app/controllers/addresses_controller.rb
app/models/address.rb
app/models/user.rb
app/views/addresses/new.html.haml
db/migrate/20200504122427_create_addresses.rb
db/schema.rb

- 送付先氏名(全角)は、ひらがな、カタカナ、漢字
- 送付先氏名(カナ)は、カタカナ
それぞれバリデーションの実装を行なった。
正しい情報をデータベースに保存するため。

アドレスフォームの正規表現

---

app/assets/javascripts/items/category_form.js

出品ページカテゴリボックスのコードを修正。
一度マージしたが人によってはローカルで動作しない、本番環境で動作しないという問題が起きたため
チーム内ではもちろん、本番環境でも同一の動きをさせる必要があるため。
コード修正前
[![Screenshot from Gyazo](https://gyazo.com/0c951ae919ece76c5aef756f1619ad2d/raw)](https://gyazo.com/0c951ae919ece76c5aef756f1619ad2d)
コード修正後
[![Screenshot from Gyazo](https://gyazo.com/eb8d85f53dbbf432deada484f19b9425/raw)](https://gyazo.com/eb8d85f53dbbf432deada484f19b9425)
動作
[![Screenshot from Gyazo](https://gyazo.com/1e362ab0fa2b0b45ee42a6a5c0cb1558/raw)](https://gyazo.com/1e362ab0fa2b0b45ee42a6a5c0cb1558)

出品ページカテゴリボックス修正

---

Gemfile
Gemfile.lock
app/uploaders/image_uploader.rb
config/initializers/carrierwave.rb

画像の保存先の指定を行った。
- ローカル、テスト環境→ public / uploads / *
- 本番環境→ S3のバケット
画像を複数枚投稿するため、ストレージサービスを使ったほうがいいため。
フリマアプリの必須実装部分のため。

S3を用いた画像保存先の指定

---

app/controllers/items_controller.rb

商品編集が完了後に飛ぶ遷移先を
if文を使用し変える
＃Why
変更するボタンを押した後→メインページへの遷移から
変更するボタンを押した後→商品詳細ページへ遷移へ変更
商品編集後にへ詳細画面がすぐに見れるとで
編集ができたのかすぐに確認する事ができる！

商品編集のエラーハンドリング

---

spec/controllers/items_controller_spec.rb
spec/factories/categories.rb
spec/rails_helper.rb
spec/support/controller_macros.rb

商品コントローラーのテストを、「一部」作成。
カテゴリーのダミーデータ(FactoryBot)の作成。
deviseをRspecで使用できるようコードとファイルを作成。
コントローラーのテストで共通して使用できるファイルをあらかじめ作成しておくことで、開発を円滑に行えるようにするため。
[![Image from Gyazo](https://i.gyazo.com/4d5f521447c5b90d7b3d1bc2d983cb82.png)](https://gyazo.com/4d5f521447c5b90d7b3d1bc2d983cb82)

商品コントローラーのテスト(雛形の共有)

---

app/controllers/addresses_controller.rb
spec/controllers/addresses_controller_spec.rb

AddressesControllerのテストを行った。
修正した点
ログインしていない場合に住所登録ページへアクセスしようとするとtopページへリダイレクトするようにした。
ログインしていないユーザーが他のユーザーの情報を書き換えできないようにする為
テストの結果

Address controllerのテスト

---

spec/controllers/items_controller_spec.rb

商品(items)コントローラーの単体テスト。
newアクションについてのテストコードを作成。
最終課題の完成に向けて、動作にエラーが出ないかを確認するため。
必須実装ではないため、newアクションのみテストコードを作成している。
[![Image from Gyazo](https://i.gyazo.com/ec990d0d002c2f2ef7deef9ad25a7633.png)](https://gyazo.com/ec990d0d002c2f2ef7deef9ad25a7633)

商品コントローラーのテスト（newアクション）
